config/routes.rb
Rails.application.routes.draw do
  
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  get :logout, to: 'sessions#destroy'

  resources :sessions

  resources :users

  resources :posts do
  	resources :comments
  end

  root 'posts#index'

  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  scope :comment_order, -> { where(created_at: 'DESC') }
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all.order(created_at: :desc)
	end

	def new
		@post = Post.new
	end

	def create
	  @post = Post.new(post_params)

	  if 
	  	@post.save
	  	redirect_to @post
	  else
	  	render 'new'
	  end
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments.comment_order
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:login][:email])

  	if user && user.authenticate(params[:login][:password])
  		session[:user_id] = user.id
  		redirect_to root_path
  		flash[:success] = "Successfully logged in!"
  	else
  		flash.now[:error] = "Invalid email or password"
  		render 'new'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  	flash[:success] = "Successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new(params[:user])
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to root_path
  		flash[:success] = "Successfully created user!"
  	else
  		render 'new'
  	end
  end

  private 

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p class="comment_name"><strong><%= comment.name %></strong></p>
<p class="comment_body"><%= comment.body %></p>
<p class="comment_time"><%= comment.created_at.to_s %></p>

app/views/comments/_form.html.erb
<%= simple_form_for ([@post, @post.comments.build]) do |f| %>

	<%= f.input :name, placeholder: 'name' %></br>
	
	<%= f.input :body, placeholder: 'comment body', input_html: { rows: '2' } %></br>

	<%= f.button :submit, id: 'submit-comment' %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="nav col-sm-2 col-xs-1 affix" id="sidebar">

	<div class="nav hidden-xs" id="logo">
		<%= link_to root_path do %>
			<h1 class="logo-text">M.Childs</h1>
		<% end %>
	</div>

	<ul class="nav hidden-xs" id="menu-section-1">
		<li class="category">Website</li>
		<li class="nav-item"><%= link_to "Blog", root_path %></li>
		<li class="nav-item"><%= link_to "About", about_path %></li>
	</ul>

	<ul class="nav hidden-xs" id="menu-section-2">
		<li class="category">Social</li>
		<li class="nav-item"><a herf="#">Twitter</a></li>
		<li class="nav-item"><a herf="#">Instagram</a></li>
		<li class="nav-item"><a herf="#">Github</a></li>
		<li class="nav-item"><a herf="#">Email</a></li>
	</ul>

	<% if current_user %>
		<ul class="nav hidden-xs" id="admin-logout">
			<li class="nav-item" id="logout-link">
				<%= link_to logout_path do %>
					 <!-- 	<i class="material-icons col-sm-2 logout-icon">&#xE8AC;</i> -->
					Logout
				<% end %>
			</li>
		</ul>
	<% else %>
		<ul class="nav hidden-xs" id="admin-login">
			<li class="nav-item" id="login-link">
				<%= link_to login_path do %>
				 	<!-- <i class="material-icons ">&#xE8D3;</i> -->
				 	Admin Login
				<% end %>
			</li>
		</ul>
	<% end %>

	<!-- tiny only nav-->
  <ul class="nav visible-xs" id="xs-menu">
    	<li class="nav-item"><a href="#featured" class="text-center"><i class="glyphicon glyphicon-list-alt"></i></a></li>
      <li class="nav-item"><a href="#stories" class="text-center"><i class="glyphicon glyphicon-list"></i></a></li>
    	<li class="nav-item"><a href="#" class="text-center"><i class="glyphicon glyphicon-paperclip"></i></a></li>
      <li class="nav-item"><a href="#" class="text-center"><i class="glyphicon glyphicon-refresh"></i></a></li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row text-center" id="primary-container"> 

		<!-- SIDEBAR --> 
	  <div class="row-offcanvas row-offcanvas-left text-center">

	  	<%= render partial: "layouts/sidebar" %>
			
		</div>
		<!-- /SIDEBAR -->


		<!-- MAIN -->
		<div class="col-sm-10 col-xs-11 pull-right" id="main">
		

				<%= yield %>

			
		</div>
		<!-- /MAIN -->

	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>

	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving </h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.input :title, placeholder: 'title', input_html: { class: 'input-lg' } %></br>
	
	<%= f.input :body, placeholder: 'post body goes here', input_html: { rows: '8' } %></br>

	<%= f.button :submit, id: 'submit-post' %>
<% end %>

app/views/posts/_post.html.erb
<%= link_to post do %>
	<%= div_for(post, class: "panel panel-default col-md-3 col-sm-6 post-tile") do %>
		<div class="panel-body">
			<h3 class="post-title"><%= post.title %></h3>
			<h5 class="date">
				<%= post.created_at.strftime("%B, %d, %Y") %>
			</h5>
		</div>
	<% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>

	<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="index-title">Posts</h1>
		
		<%= link_to new_post_path do %>
			<div class="panel panel-default col-md-3 col-sm-6 post-tile" id="add-post">
				<div class="panel-body">
					<h3 class="add-post-text">Add</h3>
					<span class=icon-container>
						<i class="material-icons lg">&#xE145;</i>
						<!-- <i class="material-icons lg">&#xE148;</i> -->
					</span>
					<h3 class="add-post-text">New Post</h3>
				</div>
			</div>
		<% end %>

		<%= render partial: "post", collection: @posts %>

app/views/posts/new.html.erb
	<h1 class="title text-center col-sm-11">
	<%= link_to posts_path do %>
			<i class="material-icons md-48 col-sm-1" id="back-arrow">
				&#xE317;
			</i> 
	<% end %>
		New Post
	</h1>

	<div class="form-container col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>

	

app/views/posts/show.html.erb
<div class="show-post">	

	
	<%= link_to posts_path do %>
			<i class="material-icons md-48 col-md-12 pull-left" id="back-arrow">
				&#xE317;
			</i> 
	<% end %>
		
	<h1 class="title"><%= @post.title %></h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> Ago
		| <%= link_to edit_post_path(@post) do %>
				Edit
		  <% end %> |
		  <%= link_to post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } do %>
				Delete
			<% end %>
	</p>

	<article class="body">
		<%= @post.body %>
	</article>

	<div id="divider"></div>

	<div class="col-md-6 col-md-offset-3" id="comments">
		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
		<h3><%= pluralize(@post.comments.count, "Comment") %></h3>
		<%= render @post.comments %>
	</div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
	<h1 class="title text-center col-sm-11">
		<%= link_to posts_path do %>
				<i class="material-icons md-48 col-sm-1" id="back-arrow">
					&#xE317;
				</i> 
		<% end %>
		Sign Up
	</h1>

	<div class="form-container col-md-6 col-md-offset-3">
		<%= simple_form_for @user do |f| %>

			<% if @user.errors.any? %>
				<div id="errors">
					<h2><%= pluralize(@user.errors.count, "error") %> prevented this post from saving </h2>
					<ul>
						<% @user.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<%= f.input :email, placeholder: 'email', input_html: { class: 'input-lg' } %></br>
			
			<%= f.input :password, placeholder: 'password', input_html: { class: 'input-lg' } %></br>

			<%= f.input :password_confirmation, placeholder: 'confirm password', input_html: { class: 'input-lg' } %></br>

			<%= f.button :submit, id: 'submit-signup' %>
		<% end %>
	</div>